version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: database2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: match_scores
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    
    volumes:
     - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
     #- mysql-data:/var/lib/mysql
    networks:
      - backend-network2
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - "8080:80"
    networks:
      - backend-network2
    environment:
      PMA_HOST: database2
      PMA_USER: test
      PMA_PASSWORD: test
    
    depends_on:
      - database

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend2
    environment:
      DB_HOST: database2
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: match_scores
    ports:
      - "3001:3001"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend2
    ports:
      - "80:80"
    networks:
      - frontend-network2
    depends_on:
      - backend

networks:
  backend-network2: 
    driver: bridge
  frontend-network2: 
    driver: bridge

volumes:
  mysql-data: 
  my-nodejs-app: 
